config/routes.rb
Rails.application.routes.draw do
  get 'receipt/show'

  get 'welcome/index'

  root 'welcome#index'

  get 'profile', to: 'users#show'

  get 'signup', to: 'users#new'
  get 'signup/:id', to: 'users#new'
  resources :users, path: 'signup', as: :users, only: [:create]
  resources :users, except: [:new, :show]

  get 'signup-delivery', to: 'deliveries#new'
  resources :deliveries, path: 'signup-delivery', as: :deliveries, only: [:create]
  resources :deliveries, except: [:new, :show]

  resources :shipments

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'healthcheck', to: 'healthcheck#healthcheck'

  get 'receipts/:id', to: 'receipts#show'

  Rails.application.routes.draw do
    resources :delivery_locator_apis
  end

  Rails.application.routes.draw do
    resources :shipping_rates
  end

end

app/views/shared/_topmenu.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container">
        <a class="navbar-brand" href="/">EnviosYa</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">

                <% if logged_in? %>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= current_user.name %>
                    </a>
                    
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      <%= link_to 'Mi perfíl', profile_path, method: :get, class: "dropdown-item" %>

                      <% if current_user.role == 3 %>
                          <a href="/shipments/new" class="list-group-item list-group-item-action">Solicitar Envío</a>
                      <% end %>

                      <!--Delivery-->
                      <% if current_user.role == 2 %>

                          <%= link_to 'Mis Envíos', shipments_path(Shipment.all), method: :get, class: "list-group-item list-group-item-action" %>

                      <% end %>

                      <%= link_to 'Salir', logout_path, method: :delete, class: "dropdown-item" %>
                    </div>
                </li>
                <% else %>
                <li class="nav-item">
                    <a class="nav-link" href="/login">Acceder</a>
                </li>
                <li class="nav-item">
                    <%= link_to 'Registro usuario', signup_path, method: :get, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Registro cadete', signup_delivery_path, method: :get, class: "nav-link" %>
                </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/shared/_user_sidebar.html.erb
<%= image_tag(current_user.profile_picture, class: "img-thumbnail mx-auto d-block rounded-circle", style:"max-height:200px") if current_user.profile_picture? %>

<div class="list-group">
  <%= link_to 'Mi perfíl', profile_path, method: :get, class: "list-group-item" %>

  <!--Final User-->
  <% if current_user.role == 3 %>
      <a href="/shipments/new" class="list-group-item list-group-item-action">Solicitar Envío</a>
  <% end %>

  <!--Delivery-->
  <% if current_user.role == 2 %>

      <%= link_to 'Mis Envíos', shipments_path(Shipment.all), method: :get, class: "list-group-item list-group-item-action" %>

<% end %>

  <%= link_to 'Salir', logout_path, method: :delete, class: "list-group-item list-group-item-action" %>
</div>