config/routes.rb
Rails.application.routes.draw do
  get 'receipt/show'

  get 'welcome/index'

  root 'welcome#index'

  get 'profile', to: 'users#show'

  get 'signup', to: 'users#new'
  get 'signup/:id', to: 'users#new'
  resources :users, path: 'signup', as: :users, only: [:create]
  resources :users, except: [:new, :show]

  get 'signup-delivery', to: 'deliveries#new'
  resources :deliveries, path: 'signup-delivery', as: :deliveries, only: [:create]
  resources :deliveries, except: [:new, :show]

  resources :shipments

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'healthcheck', to: 'healthcheck#healthcheck'

  get 'receipts/:id', to: 'receipts#show'

  Rails.application.routes.draw do
    resources :delivery_locator_apis
  end

  Rails.application.routes.draw do
    resources :shipping_rates
  end

end

app/models/shipment.rb
class Shipment < ActiveRecord::Base

   STATUS = {:IN_COURSE => "En curso", :DELIVERED => "Entregado"}
   
   # associations
   belongs_to :sender, class_name: 'User'
   belongs_to :receiver, class_name: 'User'
   belongs_to :delivery, class_name: 'User', foreign_key: :user_id

   # needed for upload images, this maps the field with the handler
   mount_uploader :signature, PictureUploader

   # validations for the Shipment's model
   validates :from_lat, presence: true
   validates :from_long, presence: true
   validates :to_lat, presence: true
   validates :to_long, presence: true

   ### Here you can place your price logic that will consume the price for an external api
   def calculatePrice
      # at this point we only return a random value between 100 and 1000
      price = Random.new
      return price.rand(100...1000)
   end

end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController

  def new
    @shipment = Shipment.new
  end

  def create

     is_new_user = false
     receiver_email = params[:shipment][:receiver]
     receiver = User.find_by_email(receiver_email)

     if (!receiver)
       is_new_user = true

         #if the user doesn't exists, we have to create one and assign to the shipment
         # this will create a new user with an especial code for registration
         receiver = User.new
         receiver = receiver.createNewUserFromShipment receiver_email
         result = receiver.save

     end

    price = 100

     if is_new_user
       # create discount
       discount = Discount.new
       discount.sender = current_user
       discount.receiver = receiver
       discount.sender_active = false
       discount.receiver_active = true
       discount.save
       # send the email to the user who will receives the package
       UserMailer.welcome_email(receiver).deliver_now!
       MyLog.debug "Se ha creado el descuento #{discount.id}"
     end

     # Checks if the sender has a discount to be applied to the price
     has_discount = false
     # search for receiver discount
     discount_tobeused = Discount.find_by_receiver_id(current_user.id)
     if discount_tobeused != nil && discount_tobeused.receiver_active
       has_discount = true
       discount_tobeused.receiver_active = false
       discount_tobeused.sender_active = true
       discount_tobeused.save
     else
       # search for sender discount
       discount_tobeused = Discount.find_by_sender_id(current_user.id)
       if discount_tobeused != nil && discount_tobeused.sender_active
         has_discount = true
         discount_tobeused.sender_active = false
         discount_tobeused.save
       end
     end

       # Applies discount
       if has_discount
         price = price*0.50
         if @shipment.save
           flash[:success] = "Se ha solicitado el envío con un descuento del 50%!"
           MyLog.debug "Se ha aplicado un descuento del 50% al envío"
         end
       end

      #####################################################################
      begin
        url = 'http://arq-deliveries.mybluemix.net/shipments'
        response = RestClient.post url,
                                   {"shipment": {"sender":current_user.id,
                                              "receiver":receiver.id,
                                              "from_lat":params[:shipment][:from_lat],
                                              "from_long":params[:shipment][:from_long],
                                               "to_lat":params[:shipment][:to_lat],
                                               "to_long":params[:shipment][:to_long],
                                              "price":price,
                                               "delivery":Delivery.getClosestFree.user.id,

                                   }}.to_json,
                                   :content_type => "application/json"
     # rescue RestClient::Exception

      json_parsed = JSON.parse(response.body)
      @shipment = Shipment.new
      @shipment.id = json_parsed["data"]["id"]
      @shipment.user_id = json_parsed["data"]["delivery"]
      sender_id = json_parsed["data"]["sender"]
      @shipment.sender = User.find(sender_id)
      receiver_id = json_parsed["data"]["receiver"]
      @shipment.receiver = User.find(receiver_id)
      @shipment.from_long = json_parsed["data"]["from_long"]
      @shipment.from_lat = json_parsed["data"]["from_lat"]
      @shipment.to_long = json_parsed["data"]["to_long"]
      @shipment.to_lat = json_parsed["data"]["to_lat"]
      @shipment.price = json_parsed["data"]["price"]
      @shipment.status = json_parsed["data"]["status"]

      ###########################################################################


     flash[:success] = "Se ha solicitado el envío"
     MyLog.debug "Se ha solicitado el envío"
    redirect_to :action => :show, :id => json_parsed["data"]["id"]
    else
      flash[:alert] = 'No se ha podido crear el envío!'
      end
  end

  def show

    begin
      url = "http://arq-deliveries.mybluemix.net/shipments/#{params[:id]}"
      response = RestClient.get url,:content_type => "application/json"
      json_parsed = JSON.parse(response.body)
      @shipment = Shipment.new
      @shipment.id = json_parsed["data"]["id"]
      @shipment.user_id = json_parsed["data"]["delivery"]
      sender_id = json_parsed["data"]["sender"]
      @shipment.sender = User.find(sender_id)
      receiver_id = json_parsed["data"]["receiver"]
      @shipment.receiver = User.find(receiver_id)
      @shipment.from_long = json_parsed["data"]["from_long"]
      @shipment.from_lat = json_parsed["data"]["from_lat"]
      @shipment.to_long = json_parsed["data"]["to_long"]
      @shipment.to_lat = json_parsed["data"]["to_lat"]
      @shipment.price = json_parsed["data"]["price"]
      @shipment.status = json_parsed["data"]["status"]


      rescue RestClient::Exception

      if (@shipment != nil)
        if (current_user.id == @shipment.sender.id) || (current_user.id == @shipment.receiver.id) || (current_user.id == @shipment.delivery.id)
          render 'show'
        else
          flash[:danger] = "No tienes permisos para realizar la acción requerida"
          redirect_to root_path
        end
      else
        flash[:danger] = "No tienes permisos para realizar la acción requerida"
        redirect_to root_path
      end

    end
  end

  def index
    is_delivery?

    begin
      url = "http://arq-deliveries.mybluemix.net/shipments"
      response = RestClient.get url,:content_type => "application/json"
      json_parsed = JSON.parse(response.body)

      shipments_collection = []

      # acceder a data
      collection = json_parsed['data']

      # iterar sobre el set de resultados
      for row in collection do

        # instanciar cada envio
        shipment = Shipment.new

        #setear los datos
        shipment.id = row['id']
        shipment.user_id = row['delivery']

        sender_id = row['sender']
        shipment.sender = User.find(sender_id)
        receiver_id = row['receiver']
        shipment.receiver = User.find(receiver_id)

        shipment.from_long = row['from_long']
        shipment.from_lat = row['from_lat']
        shipment.to_long = row['to_long']
        shipment.to_lat = row['to_lat']
        shipment.price = row['price']
        shipment.status = row['status']
        shipment.date_created = row['date_created']
        shipment.date_delivered = row['date_delivered']
        shipment.signature = row['signature']

        #agregar a shipments_collection
        shipments_collection.push shipment

      end

      # pasar shipments_colleciton a la view
      @shipments = shipments_collection

    end
  end

  def update
    begin
      url = "http://arq-deliveries.mybluemix.net/shipments/#{params[:id]}"
      signature = params[:shipment][:signature]
      payload = JSON.generate("signature": signature)
      response = RestClient.put url,
                                payload,
                                 :content_type => "application/json"

      json_parsed = JSON.parse(response.body)
      @shipment = Shipment.new
      @shipment.id = json_parsed["data"]["id"]
      @shipment.user_id = json_parsed["data"]["delivery"]
      sender_id = json_parsed["data"]["sender"]
      @shipment.sender = User.find(sender_id)
      receiver_id = json_parsed["data"]["receiver"]
      @shipment.receiver = User.find(receiver_id)
      @shipment.from_long = json_parsed["data"]["from_long"]
      @shipment.from_lat = json_parsed["data"]["from_lat"]
      @shipment.to_long = json_parsed["data"]["to_long"]
      @shipment.to_lat = json_parsed["data"]["to_lat"]
      @shipment.price = json_parsed["data"]["price"]
      @shipment.status = json_parsed["data"]["status"]
      @shipment.signature = json_parsed["data"]["signature"]
      @shipment.date_delivered = json_parsed["data"]["date_delivered"]
      @shipment.date_created = json_parsed["data"]["date_created"]


    if @shipment.save
      flash[:success] = "Se ha entregado el envío #{@shipment.id}"
      MyLog.debug "Se ha entregado el envío #{@shipment.id}"
      #UserMailer.shipment_completed_email(@shipment).deliver_now!
      render 'show'
    end
end
  end

  private def shipment_params
    params.require(:shipment).permit(:sender, :receiver, :from_lat, :from_long, :to_lat, :to_long, :price, :status, :signature)
  end
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/views/shipments/index.html.erb
<%= render "shared/topmenu", cached: true  %>
<br>
<br>
<br>
<div class='container'>

  <h1 class="center">Detalle de Envío</h1>
  <hr>
  <div class="row">
    <div class="col-md-3 text-center">
      <%= render "shared/user_sidebar", cached: true  %>
    </div>

    <% myShipments = @shipments.select {|s| s.user_id == current_user.id} %>
    <% if myShipments.blank? %>
        <p>No existen envíos.</p>
    <% else %>

    <div class='col-md-9 mx-auto'>
      <h4>Envíos en Curso</h4>
      <table class="table">
        <thead>
        <tr>
          <th>Id</th>
          <th>Emisor</th>
          <th>Receptor</th>
          <th>Origen</th>
          <th>Destino</th>
          <th>Precio</th>
        </tr>
        </thead>
        <tbody>

        <% inProgress = @shipments.select {|s| s.status == 'En curso' && s.user_id == current_user.id} %>

        <% inProgress.each do |s| %>

            <tr>
              <td><a href="/shipments/<%= s.id %>"> <%= s.id %> </a></td>
              <td><%= s.sender.email %></td>
              <td><%= s.receiver.email %></td>
              <td><%= s.from_lat %>,<%= s.from_long %></td>
              <td><%= s.to_lat %>,<%= s.to_long %></td>
              <td><%= s.price %></td>
            </tr>

        <% end %>

        </tbody>
      </table>

      <br>

      <h4>Envíos Entregados</h4>
      <table class="table">
        <thead>
        <tr>
          <th>Id</th>
          <th>Emisor</th>
          <th>Receptor</th>
          <th>Origen</th>
          <th>Destino</th>
          <th>Precio</th>
        </tr>
        </thead>
        <tbody>

        <% completed = @shipments.select {|s| s.status == 'Entregado' && s.user_id == current_user.id} %>

        <% completed.each do |s| %>
            <% cache s do %>
            <tr>
              <td><a href="/shipments/<%= s.id %>"><%= s.id %></td>
              <td><%= s.sender.email %></td>
              <td><%= s.receiver.email %></td>
              <td><%= s.from_lat %>,<%= s.from_long %></td>
              <td><%= s.to_lat %>,<%= s.to_long %></td>
              <td><%= s.price %></td>
            </tr>
            <% end %>
        <% end %>

        </tbody>
      </table>

    </div>

    <% end %>

  </div>
</div>
</div>

app/views/shipments/new.html.erb
<%= render "shared/topmenu", cached: true  %>
<br>
<br>
<br>
<div class='container'>

  <h1 class="center">Solicitar Envío</h1>
  <hr>
  <div class="row">

    <div class="col-md-3 text-center">
      <%= render "shared/user_sidebar", cached: true  %>
    </div>

    <div class='col-md-6 mx-auto'>
      <% if flash[:success] %>
          <div class="alert alert-success" role="alert">
            <%= flash[:success] %>
          </div>
      <% end %>
      <% if flash[:alert] %>
          <div class="alert alert-warning" role="alert">
            <%= flash[:alert] %>
          </div>
      <% end %>


      <%= form_for(@shipment, :html => {role: "form", multipart: true}) do |s| %>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="">
                  Receptor
                </label>
                <%= s.email_field :receiver, class: "form-control", placeholder: "Ingrese el email del receptor", autofocus: true %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="">
                  Origen
                </label>
                <%= s.gmap_coordinate_picker :lat_column => 'from_lat', :lng_column => 'from_long', :zoom_level => 10, :default_coordinates => [-34.901112, -56.164532], autocomplete: {enable: true, class: 'form-control'} %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="">
                  Destino
                </label>
                <%= s.gmap_coordinate_picker :lat_column => 'to_lat', :lng_column => 'to_long', :zoom_level => 10, :default_coordinates => [-34.901112, -56.164532], autocomplete: {enable: true, class: 'form-control'} %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="form-group">
              <%= s.submit "Solicitar", class: 'btn btn-primary btn-lg pull-right' %>
            </div>
          </div>

      <% end %>

    </div>
  </div>
</div>

app/views/shipments/show.html.erb
<%= render "shared/topmenu", cached: true  %>
<br>
<br>
<br>
<div class='container'>

  <h1 class="center">Detalle de Envío</h1>
  <hr>
  <div class="row">
    <div class="col-md-3 text-center">
      <%= render "shared/user_sidebar", cached: true  %>
    </div>
    <div class="col-md-9">

      <% if flash[:success] %>
          <div class="alert alert-success" role="alert">
            <%= flash[:success] %>
          </div>
      <% end %>

<!--Falta el bloque que muestra los errores-->

      <dl class="row">
        <dt class="col-sm-4">Id:</dt>
        <dd class="col-sm-8"><%= @shipment.id %></dd>

        <dt class="col-sm-4">Cadete:</dt>
        <dd class="col-sm-8"><%= User.find(@shipment.user_id).email %>  </dd>

        <dt class="col-sm-4">Emisor:</dt>
        <dd class="col-sm-8"><%= @shipment.sender.email %> </dd>

        <dt class="col-sm-4 text-truncate">Receptor:</dt>
        <dd class="col-sm-8"><%= @shipment.receiver.email %> </dd>

        <dt class="col-sm-4 text-truncate">Desde:</dt>
        <dd class="col-sm-8"><%= @shipment.from_lat %>, <%= @shipment.from_long %></dd>

        <dt class="col-sm-4 text-truncate">Hasta:</dt>
        <dd class="col-sm-8"><%= @shipment.to_lat %>, <%= @shipment.to_long %></dd>

        <dt class="col-sm-4 text-truncate">Precio:</dt>
        <dd class="col-sm-8"><%= @shipment.price %></dd>

        <dt class="col-sm-4 text-truncate">Estado:</dt>
        <dd class="col-sm-8"><%= @shipment.status %></dd>

        <% if @shipment.status == "En curso" && current_user.role == 2 %>
            <%= form_for(@shipment, url: shipment_path, method: :put, :html => {role: "form", multipart: true}) do |f| %>

                <div class="form-group">
                  <label for="">
                    Firma de Recepción
                  </label>
                  <%= f.file_field :signature, class: "form-control", accept: 'image/jpeg,image/gif,image/png' %>
                </div>

                <div class="form-group">
                  <%= f.submit "Finalizar Envío", class: 'btn btn-primary btn-sm' %>
                </div>

            <% end %>
        <% end %>
      </dl>

      </dl>
    </div>
  </div>
</div>